services:
  postgres:
    image: postgres:17 # Or your preferred version
    container_name: engineq_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: engineq
    ports:
      - "5432:5432" # Expose PostgreSQL on port 5432
    volumes:
      - engineq_postgres_data:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:3-management # Includes management UI
    container_name: engineq_rabbitmq
    ports:
      - "5672:5672" # AMQP port
      - "15672:15672" # Management UI port (optional)
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  pgadmin:
    image: dpage/pgadmin4
    container_name: engineq_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - postgres

volumes:
  engineq_postgres_data: