FROM python:3.11

COPY . /acura
WORKDIR /acura
ENV PATH="~/.local/bin/:$PATH"

# UV is a tool for managing Python virtual environments and is used widely across this project.
RUN pip install uv
RUN uv sync

ENTRYPOINT [ "uv", "run", "just", "start" ]
