# EngineQ: An AI-enabled music management system.
# Copyright (C) 2025  Mikayel Grigoryan
# 
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published
# by the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
# 
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.
# 
// For inquiries, contact: michael.grigoryan25@gmail.com
FROM python:3.11

COPY . /acura
WORKDIR /acura
ENV PATH="~/.local/bin/:$PATH"

# UV is a tool for managing Python virtual environments and is used widely across this project.
RUN pip install uv
RUN uv sync
# Run pending database migrations using dbmate
RUN uv just dbmate up

ENTRYPOINT [ "uv", "run", "just", "start" ]
